version: '3.8'

services:
  wxread:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-2.0.0}
    container_name: wxread-bot
    restart: unless-stopped
    
    # 环境变量配置
    environment:
      # 基础配置
      - READ_NUM=${READ_NUM:-40}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # 推送配置
      - PUSH_METHOD=${PUSH_METHOD:-}
      - PUSHPLUS_TOKEN=${PUSHPLUS_TOKEN:-}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - WXPUSHER_SPT=${WXPUSHER_SPT:-}
      
      # 网络配置
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      
      # 微信读书配置
      - WXREAD_CURL_BASH=${WXREAD_CURL_BASH:-}
    
    # 数据卷挂载
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro  # 只读配置目录
    
    # 网络配置
    networks:
      - wxread-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.path.insert(0, 'src'); from src.utils.logger import get_logger; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 可选：添加监控服务
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: wxread-monitoring
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - wxread-network
  #   depends_on:
  #     - wxread

networks:
  wxread-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  wxread-logs:
    driver: local
